---
title: "FE535 LAB 3"
author: "Robert Rodriguez"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
# Load the required packages
library(ggplot2)
library(quantmod)
library(gridExtra)
```

```{r }
# Download prices for the SPY ETF, dating between 1993-12-31 and 2022-12-31
getSymbols("SPY", from = "1993-12-31", to = "2022-12-31")
SPY_daily = Cl(SPY)
```

```{r}
# Compute the daily log-returns over this sample period (do not report)
SPY_daily_log_returns = diff(log(SPY_daily))
SPY_daily_log_returns = SPY_daily_log_returns[-1] # remove NA
```


```{r}
# Assume that the price follows a GBM. Calibrate the model by finding both mu and sigma (hats)
SPY_sigma_hat = sqrt(252*var(SPY_daily_log_returns)[1]) # annualized volatility
SPY_mu_hat = 252*mean(SPY_daily_log_returns) + SPY_sigma_hat^2/2 # annualized expected log return
```

```{r}
# After calibration, simulate the future price over a one-year period based on 
# the closing price from 2022-12-31.
# Create at least 1000 simulations and provide a couple of plots as a summary.
set.seed(1)
SPY_last_price = as.numeric(Cl(SPY)[nrow(SPY)])
SPY_simulated_prices = matrix(NA, nrow = 252, ncol = 1000)
for (i in 1:1000) {
  SPY_simulated_prices[,i] = SPY_last_price*exp(cumsum((SPY_mu_hat - 
                                                          SPY_sigma_hat^2/2) + 
                                                         SPY_sigma_hat*rnorm(252)))
}
SPY_simulated_prices[1:13,1:6]

# Create line plot of the first 16 simulations
ggplot(data = data.frame(SPY_simulated_prices), ) +
  geom_line(aes(x = 1:252, y = SPY_simulated_prices[,1]), color = "blue") +
  geom_line(aes(x = 1:252, y = SPY_simulated_prices[,2]), color = "red") +
  geom_line(aes(x = 1:252, y = SPY_simulated_prices[,3]), color = "green") +
  geom_line(aes(x = 1:252, y = SPY_simulated_prices[,4]), color = "orange") +
  geom_line(aes(x = 1:252, y = SPY_simulated_prices[,5]), color = "purple") +
  geom_line(aes(x = 1:252, y = SPY_simulated_prices[,6]), color = "black") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(labels = scales::number_format())
```
